---
id: d074c4ad-151e-4ea3-9c74-1d4322ca2971
version: 1.0.0
license: Apache-2.0
authors:
  - github_account: ddbj
    name: ddbj-workflow
    affiliation: DNA Data Bank of Japan
  - github_account: suecharo
    name: "Suetake, Hirotaka"
    affiliation: The University of Tokyo
    orcid: 0000-0003-2765-0049
  - github_account: tom-tan
    name: "Tanjo, Tomoya"
    affiliation: National Institute of Genetics
    orcid: 0000-0002-4421-9659
  - github_account: inutano
    name: "Ohta, Tazro"
    affiliation: Database Center for Life Science
    orcid: 0000-0003-3777-5945
  - github_account: yyoshiaki
    name: "Yasumizu, Yoshiaki"
    affiliation: Osaka University
    orcid: 0000-0002-9872-4909
  - github_account: ykohki
    name: "Yamada, Kohki"
workflow:
  name: DAT2-cwl Platanus-b iterate
  readme: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/e5ca6ce5f97ad974ffc9c91a20c2a49c66f4cf97/tool/platanus-b/assemble/README.md"
  language:
    type: CWL
    version: v1.0
  files:
    - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/e5ca6ce5f97ad974ffc9c91a20c2a49c66f4cf97/tool/platanus-b/iterate/platanus-b-iterate.cwl"
      target: platanus-b-iterate.cwl
      type: primary
  testing:
    - id: test
      files:
        - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/e5ca6ce5f97ad974ffc9c91a20c2a49c66f4cf97/tool/platanus-b/iterate/test-job.yml"
          target: test-job.yml
          type: wf_params
        - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/e5ca6ce5f97ad974ffc9c91a20c2a49c66f4cf97/test/data/DRR024501_1.fastq"
          target: DRR024501_1.fastq
          type: other
        - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/e5ca6ce5f97ad974ffc9c91a20c2a49c66f4cf97/test/data/DRR024501_2.fastq"
          target: DRR024501_2.fastq
          type: other
        - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/e5ca6ce5f97ad974ffc9c91a20c2a49c66f4cf97/test/data/platanus-b-contig.fa"
          target: platanus-b-contig.fa
          type: other
