---
id: 0a4b1819-3a94-443a-9b74-74b887226522
version: 1.0.0
license: CC0-1.0
authors:
  - github_account: suecharo
    name: Example Name
    affiliation: Example Affiliation
    orcid: 0000-0003-2765-0049
  - github_account: ddbj
    name: ddbj-workflow
    affiliation: DNA Data Bank of Japan
    orcid: DO NOT ENTER
workflow:
  name: CWL_trimming_and_qc
  repo:
    owner: ddbj
    name: yevis-cli
    commit: 645a193826bdb3f0731421d4ff1468d0736b4a06
  readme: "https://raw.githubusercontent.com/ddbj/yevis-cli/645a193826bdb3f0731421d4ff1468d0736b4a06/tests/CWL/wf/trimming_and_qc.cwl"
  language:
    type: CWL
    version: v1.0
  files:
    - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/645a193826bdb3f0731421d4ff1468d0736b4a06/tests/CWL/wf/fastqc.cwl"
      target: fastqc.cwl
      type: secondary
    - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/645a193826bdb3f0731421d4ff1468d0736b4a06/tests/CWL/wf/trimming_and_qc.cwl"
      target: trimming_and_qc.cwl
      type: primary
    - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/645a193826bdb3f0731421d4ff1468d0736b4a06/tests/CWL/wf/trimmomatic_pe.cwl"
      target: trimmomatic_pe.cwl
      type: secondary
  testing:
    - id: test_1
      files:
        - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/f23f77b021c64c6105114b21b5552e25be57f203/tests/CWL/test/wf_params.json"
          target: wf_params.json
          type: wf_params
        - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/f23f77b021c64c6105114b21b5552e25be57f203/tests/CWL/test/ERR034597_1.small.fq.gz"
          target: ERR034597_1.small.fq.gz
          type: other
        - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/f23f77b021c64c6105114b21b5552e25be57f203/tests/CWL/test/ERR034597_2.small.fq.gz"
          target: ERR034597_2.small.fq.gz
          type: other
