---
id: 245be3be-cc62-4073-84ac-de3a7b683920
version: 1.0.0
license: CC0-1.0
authors:
  - github_account: suecharo
    name: Example Name
    affiliation: Example Affiliation
    orcid: 0000-0003-2765-0049
  - github_account: ddbj
    name: ddbj-workflow
    affiliation: DNA Data Bank of Japan
    orcid: DO NOT ENTER
workflow:
  name: WDL_dockstore-tool-bamstats
  repo:
    owner: ddbj
    name: yevis-cli
    commit: 645a193826bdb3f0731421d4ff1468d0736b4a06
  readme: "https://raw.githubusercontent.com/ddbj/yevis-cli/645a193826bdb3f0731421d4ff1468d0736b4a06/tests/WDL/wf/dockstore-tool-bamstats.wdl"
  language:
    type: WDL
    version: "1.0"
  files:
    - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/645a193826bdb3f0731421d4ff1468d0736b4a06/tests/WDL/wf/dockstore-tool-bamstats.wdl"
      target: dockstore-tool-bamstats.wdl
      type: primary
  testing:
    - id: test_1
      files:
        - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/7bccb1cbae129cce0e48699d8f3f136fd4bdbff2/tests/WDL/test/wf_params.json"
          target: wf_params.json
          type: wf_params
        - url: "https://raw.githubusercontent.com/ddbj/yevis-cli/7bccb1cbae129cce0e48699d8f3f136fd4bdbff2/tests/WDL/test/tiny.bam"
          target: tiny.bam
          type: other
