---
id: 2c6be7d3-ff0a-4398-ad4b-673be45152d1
version: 1.0.0
license: CC0-1.0
authors:
  - github_account: inutano
    name: Tazro Inutano Ohta
    affiliation: "@dbcls"
    orcid: 0000-0003-3777-5945
  - github_account: suecharo
    name: Hirotaka Suetake
    affiliation: The Universitry of Tokyo
    orcid: 0000-0003-2765-0049
  - github_account: tom-tan
    name: Tomoya Tanjo
    affiliation: DDBJ
    orcid: 0000-0002-4421-9659
  - github_account: tfuji
    name: Takatomo Fujisawa
    affiliation: DDBJ
    orcid: 0000-0001-8978-3344
  - github_account: hacchy1983
    name: Tsuyoshi Hachiya
    affiliation: GAJ
    orcid: 0000-0002-5274-3266
  - github_account: kozo2
    name: Kozo Nishida
    affiliation: GAJ
    orcid: 0000-0001-8501-7319
  - github_account: manabuishii
    name: Manabu Ishii
    affiliation: GAJ
    orcid: 0000-0002-5843-4712
zenodo:
  url: "https://zenodo.org/record/6477052"
  id: 6477052
  doi: 10.5281/zenodo.6477052
  concept_doi: 10.5281/zenodo.6477051
workflow:
  name: "human-reseq: fastqSE2bam"
  readme: "https://zenodo.org/api/files/f1bb1866-d0bf-4b30-b40b-42c9b81fb89a/README.md"
  language:
    type: CWL
    version: v1.0
  files:
    - url: "https://zenodo.org/api/files/f1bb1866-d0bf-4b30-b40b-42c9b81fb89a/fastqSE2bam.cwl"
      target: fastqSE2bam.cwl
      type: primary
  testing:
    - id: test_1
      files:
        - url: "https://zenodo.org/api/files/f1bb1866-d0bf-4b30-b40b-42c9b81fb89a/wf_params.yml"
          target: wf_params.yml
          type: wf_params
