---
id: 4e40adc4-40e3-4d91-9998-56e6b7c73fde
version: 1.0.0
license: Apache-2.0
authors:
  - github_account: suecharo
    name: "Suetake, Hirotaka"
    affiliation: The University of Tokyo
    orcid: 0000-0003-2765-0049
  - github_account: inutano
    name: "Ohta, Tazro"
    affiliation: Database Center for Life Science
    orcid: 0000-0003-3777-5945
zenodo:
  url: "https://zenodo.org/record/6476917"
  id: 6476917
  doi: 10.5281/zenodo.6476917
  concept_doi: 10.5281/zenodo.6476916
workflow:
  name: Pitagora CWL - Download SRA
  readme: "https://zenodo.org/api/files/24bd45f4-6589-40fb-9730-55701fc88fa1/README.md"
  language:
    type: CWL
    version: v1.0
  files:
    - url: "https://zenodo.org/api/files/24bd45f4-6589-40fb-9730-55701fc88fa1/download-sra.cwl"
      target: download-sra.cwl
      type: primary
  testing:
    - id: test_1
      files:
        - url: "https://zenodo.org/api/files/24bd45f4-6589-40fb-9730-55701fc88fa1/download-fastq.yml"
          target: download-fastq.yml
          type: wf_params
