---
id: 4e40adc4-40e3-4d91-9998-56e6b7c73fde
version: 1.0.0
license: Apache-2.0
authors:
  - github_account: suecharo
    name: "Suetake, Hirotaka"
    affiliation: The University of Tokyo
    orcid: 0000-0003-2765-0049
  - github_account: inutano
    name: "Ohta, Tazro"
    affiliation: Database Center for Life Science
    orcid: 0000-0003-3777-5945
workflow:
  name: Pitagora CWL - Download SRA
  readme: "https://raw.githubusercontent.com/pitagora-network/pitagora-cwl/cd79f2db4b166d205456ab718e2581d6ab6e9f23/README.md"
  language:
    type: CWL
    version: v1.0
  files:
    - url: "https://raw.githubusercontent.com/pitagora-network/pitagora-cwl/cd79f2db4b166d205456ab718e2581d6ab6e9f23/tools/download-sra/download-sra.cwl"
      target: download-sra.cwl
      type: primary
  testing:
    - id: test_1
      files:
        - url: "https://raw.githubusercontent.com/pitagora-network/pitagora-cwl/cd79f2db4b166d205456ab718e2581d6ab6e9f23/workflows/download-fastq/download-fastq.yml"
          target: download-fastq.yml
          type: wf_params
