name: "yevis-publish-pr-with-nig-gpu"

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

# https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  pull-requests: read
  actions: read
  contents: write
  pages: read

jobs:
  publish:
    runs-on: self-hosted
    if: >
      (github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'nig-gpu'))
    steps:
      - name: "Run publish"
        id: publish
        run: |
          mkdir -p ./test-logs ./test-results
          SAPPORO_RUN_DIR=${GITHUB_WORKSPACE}/test-results \
            yevis publish \
              --verbose \
              --repository ${{ github.repository }} \
              --with-test \
              --from-pr ${{ github.event.pull_request.html_url }} \
              --wes-location http://172.19.7.164:1122 \
              --upload-zenodo \
              2>&1 | tee ./test-logs/yevis-log.txt
          exit ${PIPESTATUS[0]}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}

      - name: "List test results"
        run: ls -lR ./test-results > ./test-logs/test-results-list.txt

      - name: "Upload publish logs"
        uses: actions/upload-artifact@v3
        with:
          name: yevis-publish-logs
          path: test-logs/*
          if-no-files-found: ignore

      - name: "Check publish status"
        if: steps.publish.outcome != 'success'
        run: exit 1
